### ISSUE TITLE
Example Config ?

### ISSUE THREAD

**Issue by KEausW** [bigtreetech/Eddy#10]
It would be nice if you would provide an example config for the Eddy coil on the EBB36/42. 
The user manual is not very helpful.

**Comment by daduke** [comment]
did you figure it out? My coil just arrived..

**Comment by daduke** [comment]
ok there is some info in the [PDF manual](https://github.com/bigtreetech/Eddy/blob/master/BIGTRRETECH%20Eddy%20V1.0%20User%20Manual.pdf)

**Comment by KEausW** [comment]
Ja aber die erste Version der Coil-Konfig in dem PDF Manual war falsch.
Die haben es mittlerweile korregiert.

**Comment by daduke** [comment]
danke fuer die schnelle Antwort. Ich kann inzwischen mit dem Ding reden. Nur die Koexistenz mit der Klicky probe gefaellt ihm noch nicht...
