### ISSUE TITLE
Missing mcu configuration in both the manual and sample configuration making klipper restart unreliable

### ISSUE THREAD

**Issue by BrokenAutomap** [bigtreetech/Eddy#12]
The default klipper restart method for serial connections is `arduino `
Because Eddy is using usb this isn't a valid restart method causing klipper not to be able to restart without reboot of the host OS.
Instead the correct restart method is `command`
So after the correction the mcu section of the config should be as follows:

```    
[mcu eddy] 
serial: /dev/serial/by-id/ (Refer to the actual ID found in SSH or Mainsail using
the method above)
restart_method: command
```

**Comment by V1EngineeringInc** [comment]
What are your symptoms of this? I am willing to give it a test if I know what I am looking for.

**Comment by looxonline** [comment]
Thanks for reporting. We will get the documentation updated and close this issue out once the updates are uploaded.

**Comment by BrokenAutomap** [comment]
I

> What are your symptoms of this? I am willing to give it a test if I know what I am looking for.

Basically with btt eddy present without this additional line klipper fails to restart. After issuing either firmware restart or klipper restart, whatever you choose it'll stay in this "restarting" state forever. When it happens only rebooting the whole os managed to make the klipper start properly.

**Comment by dangerzau** [comment]
there is an R-pi restart method you could try instead of command.

**Comment by BTTJUSTIN** [comment]
The documentation has been updated. Thanks again for pointing out the issue
