### ISSUE TITLE
Z Endstop not working (Must calibrate probe_eddy_current first )

### ISSUE THREAD

**Issue by diegomtnz** [bigtreetech/Eddy#22]
[printer (eddy).txt](https://github.com/bigtreetech/Eddy/files/15496618/printer.eddy.txt)
Manta-M8P V2 + CB1

mcu(stm32h723xx)
Version: v0.12.0-178-g7e8c7f46

mcu eddy(rp2040)
Version: v0.12.0-166-g957475421
Host(aarch64, 64bit)

Version: v0.12.0-166-g957475421
OS: BTT-CB1 2.3.4 Bullseye

I run the command:
```
LDC_CALIBRATE_DRIVE_CURRENT CHIP=btt_eddy
SAVE_CONFIG
```
add me to printer.cfg:

> #*# <---------------------- SAVE_CONFIG ---------------------->
> #*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
> #*#
> #*# [probe_eddy_current btt_eddy]
> #*# reg_drive_current = 18

But when I try to home in the z axis I always get this message:

> Must calibrate probe_eddy_current first

**Comment by ifreislich** [comment]
You've missed a step. You still need to `PROBE_EDDY_CURRENT_CALIBRATE CHIP=btt_eddy`. You should also re-flash your stm32 mcu with the same version as your host.

krautech has an excellent guide that's easier to follow. Section 3 is where I think you're at.
[krautech's eddy setup guide](https://github.com/krautech/btt-eddy-guide?tab=readme-ov-file#z-endstop)

**Comment by krautech** [comment]
Hey,

Make sure you're placing eddy 20mm above the bed when you're doing the LDC_CALIBRATE_DRIVE_CURRENT CHIP=btt_eddy command.

It should auto generate in your printer.cfg the drive current. Yours looks like it's 18 which is very wrong so something has gone wrong in one of your earlier steps.

Reflash firmware and make sure the base of your eddy probe is exactly 20mm above the centre of your bed before you do it.

If you still have issues, come back and let me know

**Comment by diegomtnz** [comment]
https://github.com/bigtreetech/Eddy/assets/15325404/349f05ee-21c8-464f-aa40-3d6c529718ce

you can see in video,thanks

**Comment by diegomtnz** [comment]
SOLVED:
I need z offset calibration,my printer.cfg now:
#*# <---------------------- SAVE_CONFIG ---------------------->
#*# DO NOT EDIT THIS BLOCK OR BELOW. The contents are auto-generated.
#*#
#*# [probe_eddy_current btt_eddy]
#*# reg_drive_current = 16
#*# z_offset = 0.850
#*# calibrate =
#*# 	0.050000:3219502.999,0.100000:3218637.895,0.150000:3217813.333,
#*# 	0.200000:3217004.405,0.250000:3216097.985,0.300000:3215259.082,
#*# 	0.350000:3214539.599,0.400000:3213774.576,0.450000:3213022.870,
#*# 	0.500000:3212292.122,0.550000:3211543.117,0.600000:3210880.607,
#*# 	0.650000:3210167.339,0.700000:3209524.022,0.750000:3208887.566,
#*# 	0.800000:3208274.048,0.850000:3207685.914,0.900000:3207083.796,
#*# 	0.950000:3206523.057,1.000000:3205914.178,1.050000:3205389.873,
#*# 	1.100000:3204884.781,1.150000:3204363.035,1.200000:3203869.725,
#*# 	1.250000:3203366.151,1.300000:3202853.605,1.350000:3202398.485,
#*# 	1.400000:3201919.492,1.450000:3201480.975,1.500000:3201053.256,
#*# 	1.550000:3200594.807,1.600000:3200165.753,1.650000:3199709.337,
#*# 	1.700000:3199286.008,1.750000:3198910.560,1.800000:3198514.903,
#*# 	1.850000:3198150.712,1.900000:3197758.758,1.950000:3197390.839,
#*# 	2.000000:3197031.282,2.050000:3196679.911,2.100000:3196353.086,
#*# 	2.150000:3196030.354,2.200000:3195703.645,2.250000:3195367.403,
#*# 	2.300000:3195083.491,2.350000:3194790.406,2.400000:3194493.079,
#*# 	2.450000:3194226.396,2.500000:3193900.197,2.550000:3193628.500,
#*# 	2.600000:3193342.894,2.650000:3193092.407,2.700000:3192836.853,
#*# 	2.750000:3192572.462,2.800000:3192304.585,2.850000:3192034.831,
#*# 	2.900000:3191823.611,2.950000:3191589.977,3.000000:3191351.190,
#*# 	3.050000:3191152.487,3.100000:3190903.756,3.150000:3190681.405,
#*# 	3.200000:3190468.077,3.250000:3190259.802,3.300000:3190050.001,
#*# 	3.350000:3189850.527,3.400000:3189653.491,3.450000:3189470.947,
#*# 	3.500000:3189255.185,3.550000:3189065.961,3.600000:3188919.215,
#*# 	3.650000:3188703.005,3.700000:3188511.192,3.750000:3188373.851,
#*# 	3.800000:3188182.358,3.850000:3188007.329,3.900000:3187863.877,
#*# 	3.950000:3187703.384,4.000000:3187579.746,4.050000:3187403.387
#*# calibration_temp = 41.480823

**Comment by ifreislich** [comment]
Glad you figured it out. I was trying to tell you that you missed this step.

**Comment by diegomtnz** [comment]
> Me alegro de que lo hayas descubierto. Estaba tratando de decirte que te perdiste este paso.

thanks

**Comment by diegomtnz** [comment]
> Glad you figured it out. I was trying to tell you that you missed this step.

thanks

**Comment by Lebeao** [comment]
Hello, I also need your help, I'm starting to despair, I'm dealing with exactly the same problem "Must calibrate probe_eddy_current first" until then everything is clear, 
what happens next with the step "Z Offset Calibration" if that's all When I enter "PROBE_EDDY_CURRENT_CALIBRATE CHIP=btt_eddy" I get the default value 290mm z axis, what happens next?The 290mm is the max height of the z axis, if I enter a different value here it will be displayed. What am I doing wrong, please give me a tip what I can and should do, I'm new to klipper and have just finished building the Voron.
sorry for my English, I had it translated.

best regards Marco
 
![Screenshot_3](https://github.com/bigtreetech/Eddy/assets/122406843/6db568d7-8e6c-4df6-ac87-36f7bdddc9dd)
![Screenshot_4](https://github.com/bigtreetech/Eddy/assets/122406843/ecea9bf6-cdba-44ab-a3bf-ccfff6c3a846)
![Screenshot_5](https://github.com/bigtreetech/Eddy/assets/122406843/1a0ce654-079d-491a-b02f-e6ad271cb136)

**Comment by ifreislich** [comment]
You need to complete the `PROBE_EDDY_CURRENT_CALIBRATE CHIP=btt_eddy` step. It doesn't know where zero is so use the dialog and paper test to move the bed or nozzle to set the zero position.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon.
