### ISSUE TITLE
An idea - use the rapid scan idea for gantry levelling. 

### ISSUE THREAD

**Issue by dangerzau** [bigtreetech/Eddy#29]
Had a thought....  If rapid scan can rapidly scan from left to right and send that data to the host MCU... Could the probe stay in the same x and y position and for those of us with say a gantry and dual z motors take a single reading of height from say the left side.  Move to the right, then stay there in x and y and move the left z motors up or down to level the gantry to the bed accurately and rapidly.  Rather than having to go back and forth, I mean sure go back and check it has aligned properly but this seems like such a simple feature I wish I had the smarts to implement it myself :)

**Comment by krautech** [comment]
It will always have to go back and forth to take a new height but here's a fast QGL macro

**Comment by krautech** [comment]
```
[gcode_macro QUAD_GANTRY_LEVEL]
rename_existing: BASE_QUAD_GANTRY_LEVEL
gcode:
        BASE_QUAD_GANTRY_LEVEL RETRY_TOLERANCE=1
        BASE_QUAD_GANTRY_LEVEL horizontal_move_z=2
        
```

**Comment by BTTJUSTIN** [comment]
Thanks for making this suggestion. We will discuss it internally and let you know if it will be scheduled for a future firmware release

**Comment by BTTJUSTIN** [comment]
After an internal discussion we decided not to implement.

**Comment by bigtreetech** [comment]
To elaborate, there is little that can be done to optimise the existing klipper implementation. It is already highly optimal and resampling is always required.
