### ISSUE TITLE
Klipper reports: ERROR  Option 'data_rate' is not valid in section 'probe_eddy_current btt_eddy'

### ISSUE THREAD

**Issue by diegostf** [bigtreetech/Eddy#31]
I'm installing a clean version on the Hurakan (MANTA M4P), as the previous version was losing communication with the Eddy mcu, after an hour of printing (https://github.com/bigtreetech/Eddy/issues/30).
  During installation, klipper is showing several errors in [probe_eddy_current btt_eddy] and [temperature_probe btt_eddy].

Section 'temperature_probe btt_eddy' is not a valid config section
Option 'data_rate' is not valid in section 'probe_eddy_current btt_eddy'

I also had to comment on the  [probe] section (a lot of erros). 

![Error](https://github.com/bigtreetech/Eddy/assets/7763609/a6c252c1-32d9-4b7f-a2a0-71d3241e5cf3)

[klippy.log](https://github.com/user-attachments/files/15827790/klippy.log)

**Comment by krautech** [comment]
You need to be using BTTs klipper

**Comment by diegostf** [comment]
> You need to be using BTTs klipper

Yes, I'm using it. I followed the installation tutorial (https://github.com/bigtreetech/Eddy) until step 15.

**Comment by krautech** [comment]
According to your update manager you're using the master branch of klipper and not BTTs fork.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub
platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon

**Comment by Rotifox** [comment]
> According to your update manager you're using the master branch of klipper and not BTTs fork.

Please can you explain how to do what you say? I have the same problem
