### ISSUE TITLE
drive current=0 at any distance from hotbed

### ISSUE THREAD

**Issue by LBrynn** [bigtreetech/Eddy#39]
The correct version of BTT Klipper has been installed.
The EDDY USB sensor is displayed in the web interface, also its temperature.
when running the command LDC_CALIBRATE_DRIVE_CURRENT CHIP=btt_eddy - drive current = 0 at any distance from the hot bed (metal PEi plate).

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support and submit a ticket and we will be in touch with you soon.
