### ISSUE TITLE
Eddy coil with sb2209

### ISSUE THREAD

**Issue by ivindor** [bigtreetech/Eddy#4]
Is it possible to connect the eddy coil to the sb2209 board?

**Comment by krautech** [comment]
No, you will need to wait for Eddy CAN as you need an I2C port on your board (sb2209) for eddy coil to connect to.

Eddy CAN is coming soon.

**Comment by ivindor** [comment]
Wouldn't it be possible to connect via spi?

**Comment by BTTJUSTIN** [comment]
Hi, it is not avaible for the SPI
