### ISSUE TITLE
Issues with Z after BED_MESH_CALIBRATE

### ISSUE THREAD

**Issue by cjhmdm** [bigtreetech/Eddy#48]
I'm having this issue with both the USB and Coil versions of Eddy.

I'm using Eddy as both the Z endstop as well as the probe

After going through the initial calibration phase, I can correctly get my Z offset/height exactly where I expect, and, after homing, my Z position is about 2.5mm above the bed. When setting Z to 0, the nozzle touches the bed as expected.

Then, after running `BED_MESH_CALIBRATE METHOD=scan SCAN_MODE=rapid` and loading the heightmap, for some unknown reason, it arbitrarily sets my Z position to 5mm even though the actual position is still 2.5mm, so if I were to try to set Z to 0, it would move too low and destroy my print bed (ask me how I know... BTT please send me a new print bed, 377x370mm thx).

No matter what I do, the bed mesh profile incorrectly sets my Z position value to twice its actual position.

NOTE: the 2.5mm and 5mm values vary slightly. In the attached images, the first shows the initial Z position as 2.583mm (correct) and the second shows the z position as 4.973mm (incorrect). The only difference between the 2 images is the loading of the heightmap.
![Screenshot 2024-07-28 110020](https://github.com/user-attachments/assets/97e15ccd-289a-4358-aea7-a0ecf144479d)
![Screenshot 2024-07-28 110341](https://github.com/user-attachments/assets/e1c8a4c0-9de9-4e41-b64a-a3d5e905a373)

**Comment by bigtreetech** [comment]
Unable to replicate. Works perfectly when following the exact steps mentioned. Suggest completely erasing your klipper saved config section and performing the calibrations (current, z-mapping and thermal) that are mentioned in the readme guide of this repo. It sounds like there is likely something wrong with your calibration values.

Also ensure that you have followed the guide step by step and are using the appropriate macros from the guide.

If that still fails then feel free to reopen the issue and ensure that you upload your config files and klipper log file from just before you run the bed mesh until just after you scan and home.
