### ISSUE TITLE
Mount for H2V2S extruder

### ISSUE THREAD

**Issue by jk1974-tvh** [bigtreetech/Eddy#6]
I can't find the files for printing the part necessary to mount the eddy to the H2V2S extruder. There's a picture of it on the BTT website and it says the files can be found here, but unfortunately I'm not able to find them.

**Comment by Hoot0118** [comment]
yeah i cannot either its not in the 3d files at all

**Comment by BTTJUSTIN** [comment]
Sorry for this oversight. We will get the mount uploaded shortly and close this issue out once it is uploaded.

**Comment by BTTJUSTIN** [comment]
The documentation has been updated. Thanks again for pointing out the issue.
