### ISSUE TITLE
Unknown command:"TEMPERATURE_PROBE_CALIBRATE"

### ISSUE THREAD

**Issue by TheZDog** [bigtreetech/Eddy#61]
Installing btt eddy and im up to 

32. Run TEMPERATURE_PROBE_CALIBRATE PROBE=btt_eddy TARGET=56 STEP=4

and i get this error

Unknown command:"TEMPERATURE_PROBE_CALIBRATE"

Ender 3 V2 (4.2.7)

printer,cfg
https://pastebin.com/iCRwZyye

bigtreetech-eddy-main.cfg
https://pastebin.com/NPCxaBav

![image](https://github.com/user-attachments/assets/46bdabcf-ea86-44ad-a73c-63b6536f2f40)

**Comment by bigtreetech** [comment]
Update your host klipper.

**Comment by Joldiges** [comment]
> Update your host klipper.

I'm in the latest, 1.13.0, and i'm having the same issue.  
Similarly, it's not allowing for the mesh command as given
