### ISSUE TITLE
using eddy coil getting an error option pin is not valid in section probe 

### ISSUE THREAD

**Issue by kodil** [bigtreetech/Eddy#63]
cannot define eddy coil while using  bique microprobe . 
printer cfg looks like this 
[probe_eddy_current eddy]
sensor_type: ldc1612
z_offset: 1.5
#i2c_address:
i2c_mcu: EBBCan  # This value is good for the Eddy USB but would need to be adjusted for the Eddy Coil according to the MCU you have used.
i2c_bus: i2c3_PB3_PB4
x_offset: -30
y_offset: 33
#data_rate: 500

and probe looks like this

[probe]
pin:  ^!EBBCan:PB8  # NOTE FOR V2 users: Set this to ^!PC14 to set the low level trigger 
deactivate_on_each_sample: False
x_offset: -40
y_offset: -35
z_offset: 1.8  # Will be overridden when you do a PROBE_CALIBRATE
samples: 2
samples_tolerance: 0.05
samples_tolerance_retries: 3
activate_gcode:
    PROBE_DOWN
    G4 P500
deactivate_gcode:
    PROBE_UP

any ideas ? 

_

**Comment by bigtreetech** [comment]
Klipper does not support defining two probe sections. This is not an Eddy related question but a Klipper question.
