### ISSUE TITLE
gcode command QUERY_PROBE already registered on ender3S1

### ISSUE THREAD

**Issue by Fredlepp** [bigtreetech/Eddy#64]
I uncommented the section [bl touch] but klipper asks me to specify 
control pin and sensor pin of the bl touch 
and after I have this error:

"gcode command QUERY_PROBE already registered"

**Comment by Fredlepp** [comment]
section bl touch and z safe home are uncommented. klipper ask me to define sensor pin and control pin although bltouch section is uncommented, i tried to erase this section, save&restart and a total restart does'nt solve the problem

**Comment by bigtreetech** [comment]
Please read and follow all of the steps in the manual. It has all of the information you need.
