### ISSUE TITLE
PROBE_EDDY_CURRENT_CALIBRATE_AUTO CHIP=btt_eddy doesn't bring up adjustment screen on Voron/Klipper

### ISSUE THREAD

**Issue by drjeh** [bigtreetech/Eddy#65]
I'm trying to repeat the "paper test", but when I use the above command, the adjustment screen doesn't come up. Is there some magical step that I'm missing to get it to work?

Thanks, Joel

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
