### ISSUE TITLE
Probe center location missing

### ISSUE THREAD

**Issue by V1EngineeringInc** [bigtreetech/Eddy#7]
Hi, I looked at the step file, the instructions and the shop page and I see dimensions of the eddy but no indication of what we should use and the center point. Trying to get an accurate offset.

I took mine apart, and I see the center of the coil looks to be 4.8mm from the front of the PCB which means it is about 11.4cm from the back of the probe.

I assume left to right, it is in the center of the footprint?

**Comment by ivindor** [comment]
![48ad1594-9306-4680-824a-7a84406533f7](https://github.com/bigtreetech/Eddy/assets/70163648/e6f361e9-c96d-44b8-850c-be506a54a1cd)

**Comment by V1EngineeringInc** [comment]
All the edges other than the backplate are tapered for mold release, the best place to have accurate dimensions is the back.

I am using the dimensions I listed, just trying to let BTT know they are missing a critical piece of info.

**Comment by haynesdavid** [comment]
are you having good results? centre and 9.5 mm from the back. i started with my offset 4mm forward of that as stole someone elses config. think that worked slightly better although need to test more.

**Comment by V1EngineeringInc** [comment]
I am not sure how to test it with a lot of precision but I actually just pulled one apart again and measured the assembly. I got 11.4mm from the backplate to the center of the coil.

I updated the first post with the corrected info.

**Comment by haynesdavid** [comment]
hmmm, thats in the middle of my 4mm i guess. will also try.

**Comment by V1EngineeringInc** [comment]
I tried to take a picture so you could verify but I just don't have enough hands!

**Comment by V1EngineeringInc** [comment]
Fixed here, https://github.com/bigtreetech/Eddy/commit/516355262bbe5b122a30733da37a058067cdf916
