### ISSUE TITLE
Failed calibration - frequency not increasing each step

### ISSUE THREAD

**Issue by chrisz99** [bigtreetech/Eddy#70]
I have the Eddy USB version. I changed toolheads and hotend recently and haven't been able to get this thing calibrated. I've tried different mounts, that raise the Eddy higher and lower, I've tried messing with the Eddy Z Offset, I've tried different mounts that make my hotend higher and lower, nothing works, I keep getting this error after the Auto Z-Offset Calibration

`12:43:55 
// temperature_probe btt_eddy: Z Calibration Temperature set to 38.71. The SAVE_CONFIG command will update the printer config file and restart the printer.
12:43:55 
!! Failed calibration - frequency not increasing each step`

I'm using USB eddy as a z home and endstop. I plan on replacing Eddy, as this has become such a headache to calibrate. Even getting it to work before the toolhead and hotend change took hours, this shouldn't be this difficult.

**Comment by chrisz99** [comment]
Turns out the issue was because the black wire on the USB cabling broke off. Very unimpressed with this probe, owned it for all of 2-3 weeks. I'm going to be replacing this prove with the cartographer 3d, I suggest yall do the same.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
