### ISSUE TITLE
Eddy Coil Settings for EBB36 (solution in post)

### ISSUE THREAD

**Issue by QuinFromCanada** [bigtreetech/Eddy#71]
The documentations do not cover the Eddy Coil setup well, can the example please be added to sample config, or the manual, thank you.

**SOLUTION:**

1. Update your EBB36 firmware, eddy current probe native support was added to mainline klipper recently, and this will not work if you have an old version on your toolhead board.  I got it to work no problems with mainline klipper version 0.12.0-297

2. Use whatever BTT sample file you like, but make the following changes for Eddy Coil:

Leave [MCU] section commented out since Eddy Coil is a sensor and not an MCU.
`#[mcu eddy]`

I used an EBB36 v1.2 so I used the following settings:
```
[probe_eddy_current btt_eddy]
sensor_type: ldc1612
#i2c_address:
i2c_mcu: ebb36  # whatever you called you EBB36 mcu in my case it was [mcu ebb36]
i2c_bus: i2c3_PB3_PB4 # I2C bus for ebb36 v1.2
#i2c_speed: 400000  # didn't need this, so left it commented out.
#i2c_bus: i2c0f # didn't need this, so left it commented out.
# For a standard Voron stealthburner X carriage mount there should be no need to change the defaults below.
x_offset: 0
y_offset: 21.42
z_offset: 1.0
```

Hope this helps, anyone having issues.
Cheers!

**Comment by bigtreetech** [comment]
Every single point here is already in the manual and config files though:

<img width="571" alt="image" src="https://github.com/user-attachments/assets/7a7e9aa9-7e12-4305-8471-275f1ea57af7">


![image](https://github.com/user-attachments/assets/14113a5f-2921-459a-85e3-8baf23854959)

![image](https://github.com/user-attachments/assets/170f51c0-5004-4f66-98ac-5c5261d05421)

**Comment by digiexchris** [comment]
> Every single point here is already in the manual and config files though:
> <img alt="image" width="571" src="https://private-user-images.githubusercontent.com/38851044/367854637-7a7e9aa9-7e12-4305-8471-275f1ea57af7.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjYzNzUwNzUsIm5iZiI6MTc2NjM3NDc3NSwicGF0aCI6Ii8zODg1MTA0NC8zNjc4NTQ2MzctN2E3ZTlhYTktN2UxMi00MzA1LTg0NzEtMjc1ZjFlYTU3YWY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMjIyVDAzMzkzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlkMzM3ZmViNTZmZDQxMjE1OWM0MjU0NGZkYjFlYTFhM2VhZjVkMzIzNjZmOWE5MjYwZmIzOGI1MWI5NzBhM2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.VpDNLut7o36Fjt6lnRGNoZYuzHfAh3N_ZBLuFCTY-3s">
> 
> ![image](https://github.com/user-attachments/assets/14113a5f-2921-459a-85e3-8baf23854959)
> 
> ![image](https://github.com/user-attachments/assets/170f51c0-5004-4f66-98ac-5c5261d05421)

I don't see in the config files or the manual where it shows the I2C bus for the ebb36. The sections you quoted state only that they need to be changed if you're using the Eddy Coil, not what they need to be changed to. The examples and the manual are not clear on this. The only way I was able to figure out how to configure this for my ebb36 is by the values shown by [QuinFromCanada](https://github.com/QuinFromCanada). Could you please add this example to either you ebb36 config or your eddy coil example configs?

**Comment by violentsloth** [comment]
you dont have to program anything for the eddy coil. and you only have to mess with firm ware if you are using the other 2 versions. for the coil you just put the mcu its connected to in the name. then put in your specific values for the min max and what pin is the SDA and SCL thats it. then calibrate it your done. print some ishhhhhhhhhhhhhhhhh.

**Comment by QuinFromCanada** [comment]
> then

When when this post was made klipper did not have native eddy current scanning so things weren't as cut and dry.  Infact if memory has it right you had to install the BTT fork of klipper to get things going.

Cheers.
