### ISSUE TITLE
Make does not work

### ISSUE THREAD

**Issue by smokin76** [bigtreetech/Eddy#72]
Actually my Eddy USB is on Version: v0.12.0-297-g900bf2be5 but should be updated to Version: v0.12.0-302-g87ac69363

Using the instruction from GIT does not work anymore. After "git checkout master" and doing a "make menuconfig" i try to "make" but run into the following error:

biqu@Smok3D:~/klipper$ sudo make
  Compiling out/src/rp2040/main.o
src/rp2040/main.c:171:1: fatal error: opening dependency file out/src/rp2040/main.d: No such file or directory
 }
 ^
compilation terminated.
make: *** [Makefile:65: out/src/rp2040/main.o] Error 1
biqu@Smok3D:~/klipper$

What is the problem? First try did work flawless but now i'm stuck.

**Comment by bigtreetech** [comment]
This is seems to be a klipper related issue. Try a make clear, try deleting the repo and recreating it and also make sure that you are in the klipper directory when you send the commands. Other than that, you will need to ask on the klipper discord community why it is not making on your machine.
