### ISSUE TITLE
Unknown command:"PROBE_EDDY_CURRENT_CALIBRATE_AUTO"

### ISSUE THREAD

**Issue by helloITdepartment** [bigtreetech/Eddy#74]
Tried running step 19 from the readme (host klipper version v0.12.0-309-g064eee685) and got the error `Unknown command:"PROBE_EDDY_CURRENT_CALIBRATE_AUTO"`

**Comment by bigtreetech** [comment]
Have you copied all of the macros?

**Comment by helloITdepartment** [comment]
Nope! Completely missed that part of the file. Just found it and copied it, thanks
