### ISSUE TITLE
Error on 'PROBE_EDDY_CURRENT_CALIBRATE': missing CHIP

### ISSUE THREAD

**Issue by maj0r1337** [bigtreetech/Eddy#75]
hi there,

ive got this message in mainsail when i try to run the macro PROBE EDDY CURRENT CALIBRATE AUTO > Error on 'PROBE_EDDY_CURRENT_CALIBRATE': missing CHIP

best regards

**Comment by bigtreetech** [comment]
Duplicate of #58 and #69  and solved there.

**Comment by Dinhson178** [comment]
dear BTT. This is error macro Probe_eddy_current_calibrate_auto. You need fix it
