### ISSUE TITLE
EddyCoil with BLTouch

### ISSUE THREAD

**Issue by AnthonyTTaylor** [bigtreetech/Eddy#76]
I am trying to still use my BLTouch for my Z endstop, however when [BLTouch] is uncommented, I receive the "gcode command QUERY_PROBE already registered" even tho there is no other commands.

Unless BLTouch is doing something behind the scenes. 

Just for clarity, can I use my BLTouch for Z offset of the print head, and the Eddy for mapping the bed?

What am I missing here?

**Comment by smwoodward** [comment]
> I am trying to still use my BLTouch for my Z endstop, however when [BLTouch] is uncommented, I receive the "gcode command QUERY_PROBE already registered" even tho there is no other commands.
> 
> 
> 
> Unless BLTouch is doing something behind the scenes. 
> 
> 
> 
> Just for clarity, can I use my BLTouch for Z offset of the print head, and the Eddy for mapping the bed?
> 
> 
> 
> What am I missing here?
> 
> 
> 
> 

The problem is that you can only use one "probe" at a time in Klipper. You can have a z endstop and a probe at the same time. You could potentially make the BLtouch be a z endstop instead of a probe, but I'm not sure how you could handle the pin retraction.
