### ISSUE TITLE
[DOC UPADTE REQ] Bed severe deviation or extreme tilt

### ISSUE THREAD

**Issue by plandevida** [bigtreetech/Eddy#81]
Hi,

I just read the documentation and find this paragraph:

`Thus, scanning is not possible on beds with severe surface deviation or beds with extreme tilt that hasn't been corrected.`

Could you please clarify what’s a severe deviation or tilt on the bed?

I am planning to get the EDDY and my bed has a certain deviation, I need to know what’s the limit where eddy works fine.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
