### ISSUE TITLE
eddy x_offset, y_offset calibration

### ISSUE THREAD

**Issue by artem-sedykh** [bigtreetech/Eddy#86]
Hello, I printed a case for my eddy, please tell me how to calibrate x_offset, y_offset correctly

**Comment by ahmedbebars** [comment]
https://www.printables.com/model/1024647-btt-eddy-probe-xy-offset-tool#preview.UbBVI

**Comment by artem-sedykh** [comment]
@ahmedbebars thank you, I already made my own version https://www.printables.com/model/1040464-btteddy-creality-k1-k1c-k1-max-mount/files#preview.file.SfGca
