### ISSUE TITLE
Z-Offset Beta Doesn't Do anything at all

### ISSUE THREAD

**Issue by chrisz99** [bigtreetech/Eddy#87]
I have to use this Eddy probe because I broke my cartographer , and I don't know why the Z Offset beta features don't work. I set the Z-Offset in the variables file that is created, and nothing happens. No matter what I change that offset number too, it doesn't seem to make a difference. I have tried multiple different configurations, with multiple nozzle heights, and calibrated an infinite amount of times. This is utterly ridiculous, and is why I moved to the carto in the first place.

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
