### ISSUE TITLE
Unable to connect Eddy Coil with BTT Kraken board

### ISSUE THREAD

**Issue by ymarco73** [bigtreetech/Eddy#88]
Hi,
I'm currently experiencing trouble to install my Eddy coil version on my Kraken motherboard.
As it is connected directly to the i2c2 port of the board, I set this in the kraken cfg file:

[probe_eddy_current btt_eddy]
sensor_type: ldc1612
#i2c_address: 118
i2c_mcu: mcu
i2c_bus: i2c2_PB10_PB11
#i2c_software_scl_pin: PB10
#i2c_software_sda_pin: PB11
x_offset: 0 # Set according to the actual offset relative to the nozzle
y_offset: 20 # Set
z_offset: 2

Unfortunately, I got an error:
![image](https://github.com/user-attachments/assets/f4af89ef-874c-460e-8d1b-09d8bf1d6df8)

Here are the cfg and the klipper log files.

[config-20241025-191231.zip](https://github.com/user-attachments/files/17525526/config-20241025-191231.zip)

[klippy (4).log](https://github.com/user-attachments/files/17525472/klippy.4.log)

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
