### ISSUE TITLE
Implement 'mesh_runs'

### ISSUE THREAD

**Issue by mf7120** [bigtreetech/Eddy#89]
Hello,

Using the probe has been life changing and pretty fun to use. However I wanted to know if the feature to run the mesh multiple times and then average the results is been worked on or if it's already available somehow? Specially with the "rapid scan feature"

Thanks!

**Comment by BTTJUSTIN** [comment]
Thanks for reaching out. Our support team does not operate using the GitHub platform but we would be happy to help you via email based ticketing system. Please visit https://biqu.equipment/pages/technical-support 
and submit a ticket and we will be in touch with you soon.
