### ISSUE TITLE
Eddy CAN instructions 

### ISSUE THREAD

**Issue by serbiansky** [bigtreetech/Eddy#91]
Since you have announced and start selling CAN version of Eddy can you please update the documentation for the CAN version? I am currently building a Formbot 2.4 kit but I would like to replace TAP with Eddy CAN to simplify the wiring and I already ordered the CAN version.

**Comment by krautech** [comment]
I don't think the CAN version is shipping yet is it?

**Comment by serbiansky** [comment]
I ordered on 1 November. Should receive in few days.

**Comment by Erehr** [comment]
It will probably officialy debut during formnext (19-22.11) as one of the promo image show eddy silhouette.

**Comment by Nomanpour** [comment]
I have received the BTT Eddy Duo,
I connected it to BTT EBB SB2209, and now I can see the uuid.
`Found canbus_uuid=91464af9d0e2, Application: CanBoot`

now I want to compile the klipper firmware to flash to the eddy.

![image](https://github.com/user-attachments/assets/f1f8eab9-fe77-42ab-b386-5aab45fb225f)

What should I enter for CAN RX/TX?

**Comment by BTTJUSTIN** [comment]
The documentation has been updated. Thanks again for pointing out the issue.
